replicaCount: 1

image:
  repository: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/bilira-producer
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3001

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

metrics:
  enabled: true
  path: "/metrics"
  port: 3001

env:
  KAFKA_BROKER_URL: "kafka.default.svc.cluster.local:9092"
  KAFKA_CLIENT_ID: "producer"
  KAFKA_TOPIC: "user-events"
  LOKI_HOST: "http://loki.default.svc.cluster.local:3100" 