name: Production CI/CD

on:
  push:
    branches: [ master ]
    paths:
      - 'api/**'
      - 'producer/**'
      - 'consumer/**'
      - '.github/workflows/prod.yml'
  release:
    types: [published]

env:
  AWS_REGION: eu-central-1
  ECR_REPOSITORY_PREFIX: bilira

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api, producer, consumer]
        
    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Get AWS account ID
      id: get-aws-account
      run: |
        echo "::set-output name=account_id::$(aws sts get-caller-identity --query Account --output text)"

    - name: Deploy to EKS with Helm
      env:
        ECR_REGISTRY: ${{ steps.get-aws-account.outputs.account_id }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
        IMAGE_TAG: ${{ github.sha }}
      run: |
        helm upgrade --install ${{ matrix.service }} ../../k8s/helm/${{ matrix.service }} \
          --set image.repository=$ECR_REGISTRY/bilira-${{ matrix.service }} \
          --set image.tag=$IMAGE_TAG \
          --namespace default \
          --wait

        # Deployment'ı kontrol et
        kubectl rollout status deployment/${{ matrix.service }} -n default

  